server:
  port: 8081

spring:
  datasource:
    url:
    password:
  redis:
    database: 1
    host: 192.168.17.144
    port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl